// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetDocumentDidOrDidDocumentHandlerFunc turns a function with the right signature into a get document did or did document handler
type GetDocumentDidOrDidDocumentHandlerFunc func(GetDocumentDidOrDidDocumentParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDocumentDidOrDidDocumentHandlerFunc) Handle(params GetDocumentDidOrDidDocumentParams) middleware.Responder {
	return fn(params)
}

// GetDocumentDidOrDidDocumentHandler interface for that can handle valid get document did or did document params
type GetDocumentDidOrDidDocumentHandler interface {
	Handle(GetDocumentDidOrDidDocumentParams) middleware.Responder
}

// NewGetDocumentDidOrDidDocument creates a new http.Handler for the get document did or did document operation
func NewGetDocumentDidOrDidDocument(ctx *middleware.Context, handler GetDocumentDidOrDidDocumentHandler) *GetDocumentDidOrDidDocument {
	return &GetDocumentDidOrDidDocument{Context: ctx, Handler: handler}
}

/*GetDocumentDidOrDidDocument swagger:route GET /document/{DidOrDidDocument} getDocumentDidOrDidDocument

Fetches the latest DID Document of a DID.

*/
type GetDocumentDidOrDidDocument struct {
	Context *middleware.Context
	Handler GetDocumentDidOrDidDocumentHandler
}

func (o *GetDocumentDidOrDidDocument) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetDocumentDidOrDidDocumentParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
