// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/trustbloc/sidetree-node/models"
)

// PostDocumentOKCode is the HTTP code returned for type PostDocumentOK
const PostDocumentOKCode int = 200

/*PostDocumentOK created

swagger:response postDocumentOK
*/
type PostDocumentOK struct {

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewPostDocumentOK creates PostDocumentOK with default headers values
func NewPostDocumentOK() *PostDocumentOK {

	return &PostDocumentOK{}
}

// WithPayload adds the payload to the post document o k response
func (o *PostDocumentOK) WithPayload(payload *models.Response) *PostDocumentOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post document o k response
func (o *PostDocumentOK) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostDocumentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostDocumentBadRequestCode is the HTTP code returned for type PostDocumentBadRequest
const PostDocumentBadRequestCode int = 400

/*PostDocumentBadRequest Bad Request

swagger:response postDocumentBadRequest
*/
type PostDocumentBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostDocumentBadRequest creates PostDocumentBadRequest with default headers values
func NewPostDocumentBadRequest() *PostDocumentBadRequest {

	return &PostDocumentBadRequest{}
}

// WithPayload adds the payload to the post document bad request response
func (o *PostDocumentBadRequest) WithPayload(payload *models.Error) *PostDocumentBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post document bad request response
func (o *PostDocumentBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostDocumentBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostDocumentInternalServerErrorCode is the HTTP code returned for type PostDocumentInternalServerError
const PostDocumentInternalServerErrorCode int = 500

/*PostDocumentInternalServerError Internal server error

swagger:response postDocumentInternalServerError
*/
type PostDocumentInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostDocumentInternalServerError creates PostDocumentInternalServerError with default headers values
func NewPostDocumentInternalServerError() *PostDocumentInternalServerError {

	return &PostDocumentInternalServerError{}
}

// WithPayload adds the payload to the post document internal server error response
func (o *PostDocumentInternalServerError) WithPayload(payload *models.Error) *PostDocumentInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post document internal server error response
func (o *PostDocumentInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostDocumentInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
