// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Sidetree API
SecureKey SideTree Node


    Schemes:
      http
      https
    Host: localhost
    BasePath: /.sidetree
    Version: 0.1.0

    Consumes:
    - application/json

    Produces:
    - application/jose
    - application/json

swagger:meta
*/
package restapi
