// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Sidetree API
Sidetree Node


    Schemes:
      http
      https
    Host: localhost
    BasePath: /.sidetree
    Version: 0.1.0

    Consumes:
    - application/json

    Produces:
    - application/did+ld+json
    - application/jose

swagger:meta
*/
package restapi
