# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
swagger: "2.0"
info:
  description: Sidetree Node
  version: 0.1.0
  title: Sidetree API
basePath: /.sidetree
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /document:
    post:
      description: Create side tree did document
      produces:
        - application/json
        - application/jose
      parameters:
        - in: body
          name: request
          description: create sidetree document
          required: true
          schema:
            $ref: '#/definitions/Request'
      responses:
        200:
          description: created
          schema:
            $ref: '#/definitions/Response'
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/Error'

  /document/{DidOrDidDocument}:
    get:
      parameters:
        - in: path
          name: DidOrDidDocument
          description: DidOrDidDocument can either be
            1. Fully qualified DID
            2. An encoded DID Document prefixed by the DID method name
          required: true
          type: string
      description: Fetches the latest DID Document of a DID.
      produces:
        - application/did+ld+json
      responses:
        200:
          description: Returns the did document
          schema:
            $ref: '#/definitions/Response'
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        404:
          description: Not found
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Internal server error
          schema:
           $ref: '#/definitions/Error'
definitions:
  Request:
    type: object
    required:
      -  payload
      -  signature
      -  header
    properties:
      header:
        $ref: '#/definitions/Header'
      payload:
        type: string
      signature:
        type: string
  Header:
    type: object
    required:
      - alg
      - kid
      - operation
    properties:
      operation:
        $ref: '#/definitions/OperationType'
      kid:
        type: string
      alg:
        type: string
  OperationType:
    type: string
    enum : [ "create", "update", "delete", "recover" ]
  Error:
    type: object
    required:
      - message
    properties:
      message:
        type: string
  Response:
    type: object
    properties:
      body:
        type: object
